name: Demo-Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: #job name, kann beliebig sein
    runs-on: ubuntu-latest
    steps:
    #each step is either an action (defined by uses: action/actionName@Version) or command executed on machine via run:
      - name: Checkout Repo 
        uses: actions/checkout@v5 #checks out repo to action runner machine
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto
          cache: maven
      - name: Test with Maven
        run: mvn -B verify